// Strings.swift — the interface in English, and in Chinese.
//
// The same two-language rule as the web app: English by default, Chinese
// one switch away, and the choice changes the interface only — a post
// stays on chain in the language it was written in. Both dictionaries
// carry exactly the same keys (a test holds them to it), and an entry with
// parts is a template with `{name}` slots rather than a sentence glued
// together at the call site, so a translation can put the parts in a
// different order.

import Foundation

public struct Strings: Sendable {
    public let lang: Lang

    public init(_ lang: Lang) {
        self.lang = lang
    }

    /// The entry for `key`, with `{slot}`s filled in.
    public func t(_ key: String, _ args: [String: String] = [:]) -> String {
        let table = lang == .zh ? Strings.zh : Strings.en
        var out = table[key] ?? Strings.en[key] ?? key
        for (name, value) in args {
            out = out.replacingOccurrences(of: "{\(name)}", with: value)
        }
        return out
    }

    public subscript(_ key: String) -> String { t(key) }

    /// The name of a chain in this language: a mainnet is a proper noun.
    public func chain(_ id: Int) -> String {
        Chains.chain(id: id)?.name ?? t("chain.unknown", ["id": String(id)])
    }

    /// "Ethereum and Taiko".
    public func joinChains(_ ids: [Int]) -> String {
        let names = ids.map(chain)
        if names.count <= 1 { return names.first ?? "" }
        return names.dropLast().joined(separator: lang == .zh ? "、" : ", ") + t("common.joinAnd") + names.last!
    }

    /// `n` of something, with the one plural English has.
    public func count(_ n: Int, _ singular: String, _ plural: String) -> String {
        lang == .zh ? "\(n) \(t(singular))" : "\(n) \(t(n == 1 ? singular : plural))"
    }

    public static let en: [String: String] = [
        "brand": "Xueni",
        "tab.read": "Read",
        "tab.following": "Following",
        "tab.search": "Search",
        "tab.write": "Write",
        "tab.settings": "Settings",

        "common.retry": "Retry",
        "common.cancel": "Cancel",
        "common.done": "Done",
        "common.save": "Save",
        "common.add": "Add",
        "common.remove": "Remove",
        "common.close": "Close",
        "common.loading": "Loading…",
        "common.untitled": "Untitled",
        "common.joinAnd": " and ",
        "common.post": "post",
        "common.posts": "posts",
        "common.image": "image",
        "common.images": "images",
        "common.author": "author",
        "common.authors": "authors",
        "common.copied": "Copied",
        "common.block": "Block {block}",

        "feed.title": "Latest posts",
        "feed.subtitleAll": "All authors · {count} networks",
        "feed.viewAll": "All networks",
        "feed.onlyChain": "{chain} only",
        "feed.emptyEver": "Nothing has been published yet",
        "feed.emptyRange": "No posts in the blocks scanned so far",
        "feed.scanEarlier": "Keep scanning earlier blocks",
        "feed.note": "Read {blocks} blocks on {chain} without finding an earlier post — you can keep loading.",
        "feed.jobMore": "Scanning for earlier posts…",
        "feed.jobGap": "Filling in the blocks in between…",
        "feed.jobRefresh": "Scanning the most recent blocks…",
        "feed.readFailed": "{chain} could not be read: {reason}",
        "feed.gapPending": "{chain}: {blocks} blocks in between are still unscanned",
        "feed.scanThisRange": "Scan this range",
        "loadMore.label": "Load earlier posts",
        "loadMore.noMore": "No more posts",

        "frontier.readFailed": "{names} could not be read: {reason}",
        "frontier.authorScanning": "Still reading posts on {names} — the rows below do not include them yet",
        "frontier.feedScanning": "{names} is running its first scan — the rows below do not include it yet",
        "frontier.authorIncomplete": "Earlier posts on {names} have not been read yet",
        "frontier.feedIncomplete": "The posts below may be incomplete: {names} has only been scanned back to {when}",
        "frontier.continueReading": "Keep reading",
        "frontier.continueScanning": "Keep scanning",

        "scanProgress.blockRange": "Blocks {from} to {to}",
        "scanProgress.block": "Block {block}",
        "scanProgress.read": " · {fetched} of at most {budget} blocks read",

        "author.postsBy": "Posts by",
        "author.total": "{count} posts",
        "author.empty": "This address has never published",
        "author.jobRefresh": "Reading the list of posts…",
        "author.openExplorer": "View on {explorer}",
        "author.copyAddress": "Copy address",

        "post.by": "By",
        "post.loadFailed": "Could not load: {reason}",
        "post.transaction": "Transaction",
        "post.fromCache": "From the local cache",
        "post.notFound": "No such post",
        "post.notFoundBody": "That transaction holds no publish record, or the hash is wrong.",
        "post.locating": "Looking up this transaction…",
        "post.prev": "Previous",
        "post.next": "Next",
        "post.index": "#{index}",
        "post.viaHook": "Through the hook",
        "post.relayedBy": "Sent on the author’s behalf by",
        "post.tags": "Tags",
        "post.imageFailed": "An image on chain could not be read",
        "post.imageCaption": "Image from this post",

        "raw.show": "Raw",
        "raw.title": "As the chain holds it",
        "raw.compressed": "{bytes} on chain",
        "raw.decompressed": "{bytes} of text",
        "raw.ratio": "{ratio}× compression",
        "raw.call": "Call {call}",
        "raw.hook": "hook {hook}",
        "raw.hookData": "{bytes} of hook data",
        "raw.relayed": "Signed by {author}, sent by {sender}",
        "raw.deadline": "valid until {when}",
        "raw.copyText": "Copy the document",

        "share.label": "Share",
        "share.copyLink": "Copy link",
        "share.copyRef": "Copy reference",
        "share.exportMarkdown": "Save as .md",
        "share.reply": "Reply",

        "hook.multiName": "Fan-out (several hooks)",

        "relations.inReplyTo": "In reply to",
        "relations.continuesFrom": "Continues from",
        "relations.supersedesLine": "Supersedes",
        "relations.partOf": "Part {part} of {series}",
        "relations.inSeries": "Part of {series}",
        "relations.language": "Language",
        "relations.supersededBy": "A newer version of this post exists",
        "relations.replies": "Replies",
        "relations.continuedIn": "Continued in",
        "relations.seriesHeading": "More of {series}",
        "relations.knownHere": "Among the posts this phone has read.",

        "following.follow": "Follow",
        "following.following": "Following",
        "following.title": "Following",
        "following.subtitle": "{count} authors",
        "following.empty": "You are not following anyone yet",
        "following.emptyBody": "Follow an author from their page and their posts appear here. It costs one read per author — no block ranges are scanned at all.",
        "following.nothingYet": "Nothing from them yet",
        "following.nothingYetBody": "The authors you follow have not published anything that has been read here.",
        "following.newSince": "Read up to here {when}",
        "following.reading": "Reading their posts…",
        "following.settingsNote": "Kept on this phone only, and carried in the settings file. Following someone costs nothing and tells them nothing.",
        "following.none": "Nobody yet.",
        "following.silent": "{count} have not published yet",

        "search.title": "Search",
        "search.placeholder": "A word from a title, a tag, or the text",
        "search.scope": "Among the {count} posts this phone has read",
        "search.none": "Nothing read here contains “{query}”",
        "search.noneBody": "Read further back and this page will find more.",
        "search.tagCloud": "The tags seen so far",
        "search.noTagsYet": "No tags yet — open a few posts and they will appear here.",
        "search.goToAuthor": "Open the author {who}",
        "search.goToPost": "Open the post {what}",
        "search.resolvingName": "Looking up the name…",
        "search.noSuchName": "No such name: {name}",
        "tag.title": "Tagged {tag}",
        "tag.none": "Nothing read here carries the tag {tag}",

        "write.title": "Write",
        "write.titleField": "Title",
        "write.titlePlaceholder": "What do I want to say",
        "write.titleBytes": "{used} / {max} bytes",
        "write.titleTooLong": "The title is too long to encode as bytes32",
        "write.tagsField": "Tags",
        "write.tagsPlaceholder": "Comma to separate",
        "write.bodyField": "Body",
        "write.bodyPlaceholder": "Write something…",
        "write.preview": "Preview",
        "write.edit": "Edit",
        "write.relations": "Relations",
        "write.relationsNote": "Optional. All of it travels in the post’s own front-matter, so a reader that does not know a field simply ignores it.",
        "write.re": "Reply to",
        "write.supersedes": "Supersedes",
        "write.prev": "Continues from",
        "write.series": "Series",
        "write.part": "Part",
        "write.lang": "Language",
        "write.refPlaceholder": "0xTRANSACTION_HASH, or a link to the post",
        "write.invalidRef": "That is not a post reference.",
        "write.estimate": "About {bytes} on chain",
        "write.estimateNote": "An estimate: the document is {text}, and brotli usually squeezes a letter to under half of that.",
        "write.savedAt": "Saved on this phone {when}",
        "write.discard": "Discard",
        "write.export": "Save as .md",
        "write.import": "Import .md…",
        "write.importDropped": "Imported, without these front-matter keys this version does not know: {keys}",
        "write.handoffTitle": "Publishing from a phone",
        "write.handoffBody": "This app reads without a wallet and writes without one too: a draft lives on this phone until you hand it on. Save it as a Markdown file and open it with “Import .md…” on the Write tab of the web app, or publish it from a terminal with the command-line tool — the bytes on chain are the same whichever way it goes.",
        "write.replaceDraft": "Replace what you are writing with this file?",
        "write.replace": "Replace",
        "write.discardConfirm": "Discard this draft?",

        "settings.title": "Settings",
        "settings.endpoints": "RPC endpoints",
        "settings.endpointsNote": "The contract sits at the same address on every chain, and both chains are one journal. Each chain can hold several endpoints: the first is used, and the reader falls back to the next when one fails. A change takes effect at the next request.",
        "settings.customized": "Customized",
        "settings.defaults": "Using the defaults",
        "settings.endpointPlaceholder": "https://your-node-url",
        "settings.addEndpoint": "Add an endpoint",
        "settings.restoreDefaults": "Restore the default endpoints",
        "settings.rescanHeading": "Scan frequency",
        "settings.rescanLabel": "Rescan delay",
        "settings.rescanMinutes": "{minutes} min",
        "settings.rescanEvery": "every time",
        "settings.rescanNote": "For this long after a scan finishes, reopening the feed or an author page shows what that scan found instead of asking the node for new blocks. This only decides when new blocks are read — no post is ever missed: what has been read is kept permanently, because on-chain data does not change.",
        "settings.languageHeading": "Language",
        "settings.languageNote": "The interface only — a post is stored on chain in the language it was written in.",
        "settings.followingHeading": "Following",
        "settings.backupHeading": "Backup and restore",
        "settings.backupNote": "The endpoint lists, the rescan delay, the language and the followed authors as one JSON file — the same file the web app writes, so it restores either.",
        "settings.exportSettings": "Export settings",
        "settings.importSettings": "Import settings…",
        "settings.reviewWill": "Applying this file will:",
        "settings.apply": "Apply",
        "settings.applied": "Applied",
        "settings.archiveHeading": "Archive",
        "settings.archiveNote": "One file holding the exact stored text of every post this phone has read, and the images they refer to. It is data, not the app: any tool that reads JSON can read it. Import one and those posts open with no node at all — which is the answer to a future where public endpoints no longer serve today’s calldata.",
        "settings.archiveCounts": "{posts} posts, {images} images read on this phone",
        "settings.exportArchive": "Export everything read here",
        "settings.exportAuthor": "Export this author",
        "settings.importArchive": "Import an archive…",
        "settings.archiveApplied": "Added {posts} posts and {images} images. {skipped} were already here.",
        "settings.archiveWalking": "Reading this author back to their first post…",
        "settings.archiveReading": "Reading {done} of {total}…",
        "settings.storageHeading": "On this phone",
        "settings.storageNote": "Two databases: what has been read from the chains, which can be thrown away and read again, and what is yours — the authors you follow, the draft you are writing, the endpoints you chose.",
        "settings.cacheCounts": "{posts} posts · {bodies} bodies · {images} images · {blocks} blocks scanned",
        "settings.clearCache": "Clear the chain cache",
        "settings.clearCacheConfirm": "Forget everything read from the chains? The authors you follow and your draft stay.",
        "settings.scanPage": "Scanned ranges",
        "settings.about": "Xueni is a multi-author journal that lives entirely on Ethereum: one ownerless contract, every wallet its own author, text and images in L1 calldata. This app reads it from your own choice of nodes and keeps what it reads on this phone.",
        "settings.contract": "Contract",

        "scan.title": "Scanned ranges",
        "scan.subtitle": "The block coverage kept on this phone",
        "scan.intro": "To read posts incrementally over public RPC, the app records which block ranges it has already scanned; opening the feed again only fetches the blocks that appeared since. It records a set of ranges rather than one span: having scanned 1–100 and later 200–300, paging further back only fills in 101–199.",
        "scan.globalHeading": "Global scan (the home feed)",
        "scan.authorHeading": "Author scans",
        "scan.range": "Blocks {from} to {to}",
        "scan.summary": "{segments} ranges · {blocks} blocks · {cached} posts",
        "scan.syncedTo": "synced to block {block}",
        "scan.noRanges": "Nothing scanned yet — opening the feed records it.",
        "scan.noAuthors": "No authors yet — opening an author’s page records them.",
        "scan.budget": "Each scan reads at most {blocks} blocks from the node; the contract was deployed in block {floor}, and nothing earlier is read.",

        "archive.notJson": "Not a valid JSON file.",
        "archive.notArchive": "This is not an archive file (the xueni.archive marker is missing).",
        "archive.wrongVersion": "Archive version {version} is not supported.",
        "archive.wrongContract": "This archive is from a different deployment of the contract ({contract}).",
        "archive.droppedPosts": "Ignoring {count} posts that are malformed or on an unknown chain.",
        "archive.droppedImages": "Ignoring {count} images that are malformed or on an unknown chain.",
        "archive.empty": "The file holds no posts that can be imported.",
        "archive.chainLine": "{chain}: {posts} posts, {images} images",
        "archive.completeAuthors": "{count} authors, complete",

        "settingsFile.notJson": "Not a valid JSON file.",
        "settingsFile.notObject": "The file does not contain a settings object.",
        "settingsFile.notXueni": "This is not a Xueni settings file (the xueni.settings marker is missing).",
        "settingsFile.badFormat": "Settings file format version {format} is not supported.",
        "settingsFile.rpcsShape": "rpcs should be endpoint lists grouped by chain ID.",
        "settingsFile.unknownChain": "Skipping unknown chain ID {id}.",
        "settingsFile.chainListShape": "{chain}’s endpoint list should be an array.",
        "settingsFile.droppedEndpoints": "{chain}: ignoring {count} entries that are not http(s) URLs.",
        "settingsFile.customEndpoints": "{chain}: {count} custom endpoints",
        "settingsFile.defaultEndpoints": "{chain}: default endpoints",
        "settingsFile.rescanDelay": "Rescan delay: {minutes} minutes",
        "settingsFile.rescanShape": "rescanDelayMinutes should be a number no smaller than 0.",
        "settingsFile.lang": "Language: {lang}",
        "settingsFile.langShape": "lang should be en or zh.",
        "settingsFile.following": "Following: {count} authors",
        "settingsFile.followingShape": "following should be a list of addresses.",
        "settingsFile.followingDropped": "Ignoring {count} entries that are not addresses.",
        "settingsFile.publishChain": "Publish to: {chain} (kept for the web app)",
        "settingsFile.theme": "Theme: {theme} (kept for the web app)",
        "settingsFile.log": "Console log: {state} (kept for the web app)",
        "settingsFile.nothing": "The file holds no settings that can be applied.",

        "error.nodeBehind": "The node has not synced to block {block} yet — try again shortly.",
        "error.rateLimit": "The node is refusing requests as too frequent. Try again shortly, or change RPC endpoints in settings.",
        "error.unsupported": "This RPC endpoint does not support that kind of query — change endpoints in settings.",
        "error.unavailable": "The RPC endpoint is not responding right now. Please try again shortly.",
        "error.network": "Something went wrong with the network connection. Check it and try again.",
        "error.generic": "The node is unavailable right now. Please try again shortly.",

        "time.justNow": "just now",
        "time.about": "about {time}",
        "chain.unknown": "Chain {id}",
    ]

    public static let zh: [String: String] = [
        "brand": "雪泥",
        "tab.read": "读",
        "tab.following": "关注",
        "tab.search": "搜索",
        "tab.write": "写",
        "tab.settings": "设置",

        "common.retry": "重试",
        "common.cancel": "取消",
        "common.done": "完成",
        "common.save": "保存",
        "common.add": "添加",
        "common.remove": "删除",
        "common.close": "关闭",
        "common.loading": "加载中…",
        "common.untitled": "无标题",
        "common.joinAnd": "和",
        "common.post": "篇",
        "common.posts": "篇",
        "common.image": "张图片",
        "common.images": "张图片",
        "common.author": "位作者",
        "common.authors": "位作者",
        "common.copied": "已复制",
        "common.block": "区块 {block}",

        "feed.title": "最新文章",
        "feed.subtitleAll": "来自所有作者 · {count}个区块链网络",
        "feed.viewAll": "全部网络",
        "feed.onlyChain": "只看{chain}",
        "feed.emptyEver": "此刻还没有文章",
        "feed.emptyRange": "这一段区块里还没有文章",
        "feed.scanEarlier": "继续扫描更早的区块",
        "feed.note": "在{chain}上读取了 {blocks} 个区块，没有找到更早的文章，可以继续加载。",
        "feed.jobMore": "正在扫描更早的文章…",
        "feed.jobGap": "正在补扫中间的区块…",
        "feed.jobRefresh": "正在扫描最近区块…",
        "feed.readFailed": "{chain} 读取失败：{reason}",
        "feed.gapPending": "{chain}：中间还有 {blocks} 个区块未扫描",
        "feed.scanThisRange": "扫描这一段",
        "loadMore.label": "加载更早的文章",
        "loadMore.noMore": "没有更多文章",

        "frontier.readFailed": "{names} 读取失败：{reason}",
        "frontier.authorScanning": "正在读取{names}上的文章，以下暂未包含{names}的文章",
        "frontier.feedScanning": "{names} 正在进行第一次扫描，以下暂未包含{names}的文章",
        "frontier.authorIncomplete": "{names}上更早的文章尚未读取",
        "frontier.feedIncomplete": "以下文章可能不完整：{names} 只扫描到{when}",
        "frontier.continueReading": "继续读取",
        "frontier.continueScanning": "继续扫描",

        "scanProgress.blockRange": "区块 {from} 至 {to}",
        "scanProgress.block": "区块 {block}",
        "scanProgress.read": " · 本次已读 {fetched} / 最多 {budget} 个区块",

        "author.postsBy": "作者",
        "author.total": "共 {count} 篇",
        "author.empty": "该地址没发表过文章",
        "author.jobRefresh": "正在读取文章列表…",
        "author.openExplorer": "在 {explorer} 上查看",
        "author.copyAddress": "复制地址",

        "post.by": "作者：",
        "post.loadFailed": "加载失败：{reason}",
        "post.transaction": "交易",
        "post.fromCache": "来自本地缓存",
        "post.notFound": "没有找到这篇文章",
        "post.notFoundBody": "这笔交易里没有发布记录，或交易哈希有误。",
        "post.locating": "正在查找这笔交易…",
        "post.prev": "上一篇",
        "post.next": "下一篇",
        "post.index": "第 {index} 篇",
        "post.viaHook": "经由钩子",
        "post.relayedBy": "由他人代为发送：",
        "post.tags": "标签",
        "post.imageFailed": "链上的一张图片无法读取",
        "post.imageCaption": "文章中的图片",

        "raw.show": "原文",
        "raw.title": "链上原文",
        "raw.compressed": "链上 {bytes}",
        "raw.decompressed": "正文 {bytes}",
        "raw.ratio": "压缩 {ratio} 倍",
        "raw.call": "调用 {call}",
        "raw.hook": "钩子 {hook}",
        "raw.hookData": "钩子数据 {bytes}",
        "raw.relayed": "由 {author} 签名，由 {sender} 发送",
        "raw.deadline": "有效期至 {when}",
        "raw.copyText": "复制原文",

        "share.label": "分享",
        "share.copyLink": "复制链接",
        "share.copyRef": "复制引用",
        "share.exportMarkdown": "存为 .md",
        "share.reply": "回复这篇",

        "hook.multiName": "分发器（多个钩子）",

        "relations.inReplyTo": "回复",
        "relations.continuesFrom": "承接自",
        "relations.supersedesLine": "替代",
        "relations.partOf": "《{series}》第 {part} 篇",
        "relations.inSeries": "属于《{series}》",
        "relations.language": "语言",
        "relations.supersededBy": "这篇文章有更新的版本",
        "relations.replies": "回复",
        "relations.continuedIn": "后续",
        "relations.seriesHeading": "《{series}》的其他篇",
        "relations.knownHere": "以上来自这部手机已经读过的文章。",

        "following.follow": "关注",
        "following.following": "已关注",
        "following.title": "关注",
        "following.subtitle": "{count} 位作者",
        "following.empty": "还没有关注任何人",
        "following.emptyBody": "在作者页上点「关注」，他们的文章就会出现在这里。每位作者只需一次读取，完全不扫描区块范围。",
        "following.nothingYet": "还没有他们的文章",
        "following.nothingYetBody": "你关注的作者还没有在这里读到过的文章。",
        "following.newSince": "上次读到这里（{when}）",
        "following.reading": "正在读取他们的文章…",
        "following.settingsNote": "只保存在这部手机上，并随设置文件一起导出。关注不花费任何费用，对方也不会知道。",
        "following.none": "还没有关注任何人。",
        "following.silent": "其中 {count} 位还没发表过",

        "search.title": "搜索",
        "search.placeholder": "标题、标签或正文里的一个词",
        "search.scope": "在这部手机已读过的 {count} 篇文章中",
        "search.none": "已读过的文章里没有包含“{query}”的",
        "search.noneBody": "往前多读一些，这一页就会找到更多。",
        "search.tagCloud": "目前见过的标签",
        "search.noTagsYet": "还没有标签——打开几篇文章后就会出现。",
        "search.goToAuthor": "打开作者 {who}",
        "search.goToPost": "打开文章 {what}",
        "search.resolvingName": "正在解析名称……",
        "search.noSuchName": "没有这个名称：{name}",
        "tag.title": "标签：{tag}",
        "tag.none": "已读过的文章里没有带 {tag} 标签的",

        "write.title": "写",
        "write.titleField": "标题",
        "write.titlePlaceholder": "我想表达什么",
        "write.titleBytes": "{used} / {max} 字节",
        "write.titleTooLong": "标题太长，无法编码为 bytes32",
        "write.tagsField": "标签",
        "write.tagsPlaceholder": "逗号分隔",
        "write.bodyField": "正文",
        "write.bodyPlaceholder": "写点什么…",
        "write.preview": "预览",
        "write.edit": "编辑",
        "write.relations": "关系",
        "write.relationsNote": "都是可选的。这些字段随文章的前置数据一起上链，不认识某个字段的阅读器会直接忽略它。",
        "write.re": "回复",
        "write.supersedes": "替代",
        "write.prev": "承接自",
        "write.series": "系列",
        "write.part": "第几篇",
        "write.lang": "语言",
        "write.refPlaceholder": "0x交易哈希，或文章链接",
        "write.invalidRef": "这不是一个文章引用。",
        "write.estimate": "上链约 {bytes}",
        "write.estimateNote": "估算：文档共 {text}，brotli 通常能把一封信压到一半以下。",
        "write.savedAt": "已保存在这部手机上（{when}）",
        "write.discard": "丢弃",
        "write.export": "存为 .md",
        "write.import": "导入 .md…",
        "write.importDropped": "已导入；以下本版本不认识的前置字段被略过：{keys}",
        "write.handoffTitle": "在手机上写，在别处发",
        "write.handoffBody": "这个应用读不需要钱包，写也不需要：草稿留在这部手机上，直到你把它交出去。把它存成 Markdown 文件，在网页版「写」页用「导入 .md…」打开，或用命令行工具从终端发布——无论走哪条路，链上的字节都是一样的。",
        "write.replaceDraft": "用这个文件替换正在写的内容？",
        "write.replace": "替换",
        "write.discardConfirm": "丢弃这份草稿？",

        "settings.title": "设置",
        "settings.endpoints": "RPC 节点",
        "settings.endpointsNote": "合约在每条链上都是同一个地址，两条链读的是同一本刊物。每条链可以配置多个节点：按顺序使用第一个，失败时自动回退到下一个。修改从下一次请求起生效。",
        "settings.customized": "已自定义",
        "settings.defaults": "使用默认配置",
        "settings.endpointPlaceholder": "https://你的节点地址",
        "settings.addEndpoint": "添加节点",
        "settings.restoreDefaults": "恢复默认节点",
        "settings.rescanHeading": "扫描频率",
        "settings.rescanLabel": "扫描延迟",
        "settings.rescanMinutes": "{minutes} 分钟",
        "settings.rescanEvery": "每次都扫",
        "settings.rescanNote": "上一次扫描结束后的这段时间内，重新打开首页或作者页只显示上次扫到的文章，不再向节点请求新区块。这只决定「什么时候去读新区块」，不会漏掉任何文章：已经读到的内容是永久保存的——链上数据不会改变。",
        "settings.languageHeading": "语言",
        "settings.languageNote": "只改变界面，文章仍以写作时的语言存在链上。",
        "settings.followingHeading": "关注",
        "settings.backupHeading": "备份与恢复",
        "settings.backupNote": "各链的节点列表、扫描延迟、界面语言和关注的作者，存成一个 JSON 文件——和网页版写的是同一种文件，两边都能恢复。",
        "settings.exportSettings": "导出设置",
        "settings.importSettings": "导入设置…",
        "settings.reviewWill": "应用这个文件将：",
        "settings.apply": "应用",
        "settings.applied": "已应用",
        "settings.archiveHeading": "存档",
        "settings.archiveNote": "一个文件，装着这部手机读过的每篇文章在链上的原文，以及它们引用的图片。它是数据，不是程序：任何能读 JSON 的工具都能读它。导入后，这些文章不需要任何节点就能打开——将来公共节点不再提供今天的 calldata 时，靠的就是它。",
        "settings.archiveCounts": "这部手机已读 {posts} 篇文章，{images} 张图片",
        "settings.exportArchive": "导出这里读过的全部",
        "settings.exportAuthor": "导出这位作者",
        "settings.importArchive": "导入存档…",
        "settings.archiveApplied": "新增 {posts} 篇文章和 {images} 张图片，其中 {skipped} 篇本来就在。",
        "settings.archiveWalking": "正在把这位作者一路读到第一篇……",
        "settings.archiveReading": "正在读取 {done} / {total}……",
        "settings.storageHeading": "这部手机上",
        "settings.storageNote": "两个数据库：从链上读到的内容，可以丢掉再读；以及属于你的——关注的作者、正在写的草稿、选择的节点。",
        "settings.cacheCounts": "{posts} 篇 · {bodies} 篇正文 · {images} 张图片 · 已扫描 {blocks} 个区块",
        "settings.clearCache": "清除链上缓存",
        "settings.clearCacheConfirm": "忘掉从链上读到的一切？关注的作者和草稿会留下。",
        "settings.scanPage": "扫描范围",
        "settings.about": "雪泥是一个完全存在于以太坊上的多作者刊物：一份无主的合约，每个钱包都是作者，文字和图片都在 L1 calldata 里。这个应用从你自己选的节点读它，并把读到的留在这部手机上。",
        "settings.contract": "合约",

        "scan.title": "扫描范围",
        "scan.subtitle": "这部手机保存的区块覆盖范围",
        "scan.intro": "为了在公共 RPC 上增量读取链上文章，应用会记录已经扫描过的区块范围，再次打开首页只拉取新出现的区块。记录的是多段范围而不是一整段：先扫过 1–100、后来扫过 200–300，再往前翻时只会补上中间的 101–199。",
        "scan.globalHeading": "全局扫描（首页流）",
        "scan.authorHeading": "作者扫描",
        "scan.range": "区块 {from} 至 {to}",
        "scan.summary": "{segments} 段 · 共 {blocks} 个区块 · {cached} 篇",
        "scan.syncedTo": "已同步至区块 {block}",
        "scan.noRanges": "还没有扫描记录——打开首页后自动记录。",
        "scan.noAuthors": "还没有作者记录——打开某位作者的文章页后自动记录。",
        "scan.budget": "每次扫描最多向节点读取 {blocks} 个区块；合约部署于区块 {floor}，不会读取更早的区块。",

        "archive.notJson": "不是有效的 JSON 文件。",
        "archive.notArchive": "这不是存档文件（缺少 xueni.archive 标记）。",
        "archive.wrongVersion": "不支持版本 {version} 的存档。",
        "archive.wrongContract": "这个存档来自另一份合约部署（{contract}）。",
        "archive.droppedPosts": "忽略 {count} 篇格式错误或链未知的文章。",
        "archive.droppedImages": "忽略 {count} 张格式错误或链未知的图片。",
        "archive.empty": "文件里没有可以导入的文章。",
        "archive.chainLine": "{chain}：{posts} 篇文章，{images} 张图片",
        "archive.completeAuthors": "{count} 位作者，完整",

        "settingsFile.notJson": "不是有效的 JSON 文件。",
        "settingsFile.notObject": "文件内容不是一个设置对象。",
        "settingsFile.notXueni": "这不是雪泥的设置文件（缺少 xueni.settings 标记）。",
        "settingsFile.badFormat": "设置文件格式版本 {format} 不受支持。",
        "settingsFile.rpcsShape": "rpcs 应是按链 ID 分组的节点列表。",
        "settingsFile.unknownChain": "跳过未知的链 ID {id}。",
        "settingsFile.chainListShape": "{chain} 的节点列表应是数组。",
        "settingsFile.droppedEndpoints": "{chain}：忽略 {count} 个不是 http(s) 地址的节点。",
        "settingsFile.customEndpoints": "{chain}：{count} 个自定义节点",
        "settingsFile.defaultEndpoints": "{chain}：默认节点",
        "settingsFile.rescanDelay": "扫描延迟：{minutes} 分钟",
        "settingsFile.rescanShape": "rescanDelayMinutes 应是不小于 0 的数字。",
        "settingsFile.lang": "界面语言：{lang}",
        "settingsFile.langShape": "lang 应是 en 或 zh。",
        "settingsFile.following": "关注：{count} 位作者",
        "settingsFile.followingShape": "following 应该是一组地址。",
        "settingsFile.followingDropped": "已忽略 {count} 个不是地址的条目。",
        "settingsFile.publishChain": "发布到：{chain}（为网页版保留）",
        "settingsFile.theme": "主题：{theme}（为网页版保留）",
        "settingsFile.log": "控制台日志：{state}（为网页版保留）",
        "settingsFile.nothing": "文件里没有可应用的设置。",

        "error.nodeBehind": "节点尚未同步到区块 {block}，稍后重试即可",
        "error.rateLimit": "节点请求过于频繁，请稍后重试，或到设置里更换 RPC 节点。",
        "error.unsupported": "当前 RPC 节点不支持这类查询，请到设置里更换节点。",
        "error.unavailable": "RPC 节点暂时无法响应，请稍后重试。",
        "error.network": "网络连接出现问题，请检查网络后重试。",
        "error.generic": "节点暂时不可用，请稍后重试。",

        "time.justNow": "刚刚",
        "time.about": "约 {time}",
        "chain.unknown": "链 {id}",
    ]
}
